WeEvent/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pagina.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pagina/urls.py
from django.urls import path, include
from .views import *
from .models import *

urlpatterns = [
    path('',HomePage.as_view(),name='home'),
    path('events/',EventIndexView.as_view(),name='events_index'),
    path('events/<int:id>',EventShowView.as_view(),name='show_event'),
    path('show_event/<int:id>/', EventShowView.as_view(), name='show_event'),
    path('create_event/', CreateEventView.as_view(), name='create_event'),
    path('delete_event/<int:id>/', DeleteEventView.as_view(), name='delete_event'),
    path('like_event/<int:id>/', LikeEventView.as_view(), name='like_event'),
    path('attend_event/<int:id>/', AttendEventView.as_view(), name='attend_event'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('signup/', user_signup, name='user_signup'),
    path('edit_event/<int:id>/', EditEventView.as_view(), name='edit_event'),
    path('user_events/', UserEventsView.as_view(), name='user_events'),
    path('comunidad/',Comunidad.as_view(),name='comunidad'),

]

pagina/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User

class Evento(models.Model):
    nombre = models.CharField(max_length=255)
    ubicacion = models.CharField(max_length=255)
    fechaInicio = models.DateField()
    fechaFin = models.DateField()
    organizador = models.ForeignKey(User, on_delete=models.CASCADE)
    descripcion = models.TextField()
    imagen = models.ImageField(upload_to='pagina/static/pagina/event_images/', null=True, blank=True)
    videos = models.URLField()
    precio = models.FloatField()
    capacidad = models.IntegerField()
    asistencia = models.IntegerField(default=0)
    categorias = models.CharField(max_length=255)
    etiquetas = models.CharField(max_length=255)
    calificacion = models.IntegerField(default=0)
    puntuacion = models.FloatField(default=0)
    # comentarios = models.ManyToManyField(User, through='Comentario')

class Comentario(models.Model):
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    texto = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comentario por {self.usuario.username} en {self.evento.nombre}'
    
    #deploy
class Like(models.Model):
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.usuario.username} le gusta {self.evento.nombre}'

class Attendance(models.Model):
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.usuario.username} irá al evento {self.evento.nombre}'

pagina/forms.py
from django import forms
from .models import *

class EventoForm(forms.ModelForm):

    CATEGORIES_CHOICES = [
        ('Cultura', 'Cultura'),
        ('Fiesta', 'Fiesta'),
        ('Tecnología', 'Tecnología'),
        ('Feria', 'Feria'),
        ('Evento', 'Evento'),
        ('Conferencia', 'Conferencia'),
        ('Concierto', 'Concierto'),
        ('Deporte', 'Deporte'),
        ('Taller', 'Taller'),
        ('Exposición', 'Exposición'),
        ('Actividad', 'Actividad'),
        ('Gastronomía', 'Gastronomía'),
        ('Networking', 'Networking'),
        ('Celebración', 'Celebración'),
        ('Caridad', 'Caridad'),
        ('Teatro', 'Teatro'),
        ('Reunión temática', 'Reunión temática'),
    ]
    class Meta:
        model = Evento
        fields = ['nombre', 'ubicacion', 'fechaInicio', 'fechaFin', 'descripcion', 'precio', 'capacidad', 'categorias', 'etiquetas', 'imagen']

    def __init__(self, *args, **kwargs):
        super(EventoForm, self).__init__(*args, **kwargs)

        # Campos obligatorios y opcionales
        self.fields['nombre'].required = True
        self.fields['ubicacion'].required = True
        self.fields['fechaInicio'].required = True
        self.fields['fechaFin'].required = False
        self.fields['descripcion'].required = False
        self.fields['precio'].required = False
        self.fields['capacidad'].required = False
        self.fields['categorias'] = forms.ChoiceField(choices=self.CATEGORIES_CHOICES, required=True)
        self.fields['etiquetas'].required = False

        self.fields['fechaInicio'].widget.input_type = 'date'
        self.fields['fechaFin'].widget.input_type = 'date'

        self.fields['nombre'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Nombre del evento'
        })
        self.fields['ubicacion'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Ubicación del evento'
        })
        self.fields['fechaInicio'].widget.attrs.update({
            'class': 'form-control datepicker',
            'placeholder': 'Fecha de inicio (YYYY-MM-DD)'
        })
        self.fields['fechaFin'].widget.attrs.update({
            'class': 'form-control datepicker',
            'placeholder': 'Fecha de finalización (YYYY-MM-DD)'
        })
        self.fields['descripcion'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Descripción del evento'
        })
        self.fields['precio'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Precio del evento'
        })
        self.fields['capacidad'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Capacidad del evento'
        })
        self.fields['categorias'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Categorías del evento'
        })
        self.fields['etiquetas'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Etiquetas del evento'
        })
        self.fields['imagen'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Sube una imagen del evento'
        })


class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ['texto']
        widgets = {
            'texto': forms.Textarea(attrs={'rows': 1}),
        }

pagina/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.views.generic import TemplateView
from django.views import View
from .models import *
from .forms import *
from .recommendations.algo import do_recomendation

class HomePage(TemplateView):
    template_name = 'home.html'
    def get(self, request):
        event_with_likes = []
        id_name_events = []
        values = []
        view_data = {}

        all_events1 = Evento.objects.all().order_by('-id')[:3]
        view_data['latest'] = all_events1
        print(all_events1)
        
        
        if request.user.is_authenticated:
            user_likes = Like.objects.filter(usuario=request.user)
            user_likes = list(user_likes.values())
            for liked_events in user_likes:
                event_with_likes.append({'id':liked_events['evento_id']})

            all_events = Evento.objects.all()
            all_events = list(all_events.values())

            for event in all_events:
                id_name_events.append({'id':event['id'], 'name':event['nombre'], 'category':event['categorias']})

            recomendations = do_recomendation(event_with_likes, id_name_events, True)
            for recomendation in recomendations:
                values.append(recomendation['id'])
            filtered_events = Evento.objects.filter(id__in=values)
            view_data['recomendations'] = filtered_events

            return render(request, self.template_name, view_data)
        else:
            recomendations = do_recomendation(event_with_likes, id_name_events, False)
            for recomendation in recomendations:
                values.append(recomendation['id'])
            filtered_events = Evento.objects.filter(id__in=values)
            view_data['recomendations'] = filtered_events

            return render(request, self.template_name, view_data)

class EventIndexView(TemplateView):
    template_name = 'events_index.html'

    def get(self, request):
        viewData = {}
        viewData["subtitle"] =  "Todos los eventos"
        viewData["events"] = Evento.objects.all()

        return render(request, self.template_name, viewData)


class EventShowView(View):
    template_name = 'show_event.html'

    def get(self, request, id):
        view_data = {}
        view_data["event"] = get_object_or_404(Evento, pk=id)
        view_data["comentario_form"] = ComentarioForm()
        view_data["comentarios"] = Comentario.objects.filter(evento=view_data["event"])

        return render(request, self.template_name, view_data)

    def post(self, request, id):
        event = get_object_or_404(Evento, pk=id)
        form = ComentarioForm(request.POST)

        if form.is_valid():
            comentario = form.save(commit=False)
            comentario.evento = event
            comentario.usuario = request.user
            comentario.save()
            messages.success(request, 'Comentario agregado con éxito.')
        else:
            messages.error(request, 'Error al agregar el comentario. Por favor, verifica el formulario.')

        return redirect('show_event', id=id)

class LikeEventView(View):
    def get(self, request, id):
        evento = get_object_or_404(Evento, id=id)

        # Verifica si el usuario ya dio "Me gusta" al evento
        existing_like = Like.objects.filter(evento=evento, usuario=request.user).first()

        if existing_like:
            # Si ya dio "Me gusta", elimina el "Me gusta"
            existing_like.delete()
            evento.puntuacion -= 1  # Resta 1 a la puntuación
        else:
            # Si no ha dado "Me gusta", crea el "Me gusta"
            Like.objects.create(evento=evento, usuario=request.user)
            evento.puntuacion += 1  # Suma 1 a la puntuación

        evento.save()  # Guarda la actualización de la puntuación

        return redirect('show_event', id=id)

class AttendEventView(View):
    def get(self, request, id):
        evento = get_object_or_404(Evento, id=id)

        # Verifica si el usuario ya dio "Me gusta" al evento
        attendance = Attendance.objects.filter(evento=evento, usuario=request.user).first()

        if attendance:
            # Si ya dio "Me gusta", elimina el "Me gusta"
            attendance.delete()
            evento.asistencia -= 1  # Resta 1 a la puntuación
        else:
            # Si no ha dado "Me gusta", crea el "Me gusta"
            Attendance.objects.create(evento=evento, usuario=request.user)
            evento.asistencia += 1  # Suma 1 a la puntuación

        evento.save()  # Guarda la actualización de la puntuación

        return redirect('show_event', id=id)

@method_decorator(login_required, name='dispatch')
class EditEventView(View):
    template_name = 'edit_event.html'

    def get(self, request, id):
        evento = get_object_or_404(Evento, id=id)

        # Verificar si el usuario actual es el organizador del evento
        if request.user != evento.organizador:
            return redirect('events_index')

        form = EventoForm(instance=evento)
        return render(request, self.template_name, {'form': form, 'evento': evento})

    def post(self, request, id):
        evento = get_object_or_404(Evento, id=id)

        # Verificar si el usuario actual es el organizador del evento
        if request.user != evento.organizador:
            return redirect('events_index')

        form = EventoForm(request.POST, instance=evento)
        if form.is_valid():
            form.save()
            return redirect('show_event', id=evento.id)
        return render(request, self.template_name, {'form': form, 'evento': evento})


class CreateEventView(LoginRequiredMixin, View):
    template_name = 'create_event.html'
    login_url = '/login/'

    def get(self, request):
        form = EventoForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = EventoForm(request.POST, request.FILES)
        if form.is_valid():
            evento = form.save(commit=False)
            evento.organizador = request.user  # Asigna el organizador correctamente
            evento.save()
            messages.success(request, 'Evento creado con éxito.')
            return redirect('show_event', id=evento.id)
        else:
            messages.error(request, 'Error al crear el evento. Por favor, verifica el formulario.')

        return render(request, self.template_name, {'form': form})


@method_decorator(login_required, name='dispatch')
class DeleteEventView(View):
    def get(self, request, id):
        evento = get_object_or_404(Evento, id=id)

        # Verificar si el usuario actual es el creador del evento
        if request.user == evento.organizador:
            evento.delete()
            messages.success(request, 'Evento eliminado con éxito.')
        else:
            messages.error(request, 'No tienes permisos para eliminar este evento.')

        return redirect('events_index')

def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})

def user_logout(request):
    logout(request)
    return redirect('home')

def user_signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

class UserEventsView(View):
    template_name = 'user_events.html'

    def get(self, request):
        user_events = Evento.objects.filter(organizador=request.user)
        return render(request, self.template_name, {'user_events': user_events})

@method_decorator(login_required, name='dispatch')
class Comunidad(View):
    template_name = 'comunidad.html'

    def get(self, request):
        viewData = {}
        viewData["comentarios"] = Comentario.objects.all().order_by('-fecha_creacion')
        viewData["likes"] = Like.objects.all().order_by('-id')
        
        return render(request, self.template_name, viewData)

pagina/templates/base.html
{% load static %} 
<!doctype html> 
<html lang="en"> 
<head> 
  <meta charset="utf-8" /> 
  <meta name="viewport" content="width=device-width, initial-scale=1" /> 
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous" />
   
  <title>{% block title %}'WeEvent'{% endblock %}</title>
</head>
<body style="background-image: url(https://img.freepik.com/vector-gratis/fondo-monocromatico-blanco-degradado_23-2149009182.jpg?w=1380&t=st=1700584631~exp=1700585231~hmac=fbd06db41e31fec173980b037a6279452995956a9541f66150cde1df962a7567); background-size: cover; ">
  <!-- header -->
  <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">We Event </a>
      <img src="https://cdn.discordapp.com/attachments/1073616258223833089/1153840624806674443/image.png" alt="imagenNavbar"  width="30" height="24" class="rounded-circle">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'events_index' %}">Eventos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'comunidad' %}">Comunidad</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'create_event' %}">Crear Eventos</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user_events' %}">Mis Eventos</a>
            </li>
        {% endif %}
          {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Cerrar sesión</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Iniciar sesión</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user_signup' %}">Registrarse</a>
                </li>
            {% endif %}
        </ul>
      </div>
    </div>
  </nav>
 
  <header class="masthead bg-primary text-white text-center py-4"> 
    <div class="container d-flex align-items-center flex-column"> 
      <h2>{% block header_title %}'Eventos que te pueden gustar'{% endblock %}</h2> 
    </div> 
  </header> 
  <!-- header --> 
 
  <div class="container my-4"> 
    {% block content %} 
    {% endblock %} 
  </div> 
 
<!-- footer --> 
  {% block footer %} 
  <div class="copyright py-4 text-center text-white"> 
    <div class="container"> 
    </div> 
  </div> 
  <!-- footer --> 
  {% endblock %} 
  </script> 
</body> 
</html> 

pagina/templates/comunidad.html
{% extends 'base.html' %}
{% block title %}
    Foro de la Comunidad
{% endblock %}
{% block header_title %}Comunidad{% endblock %}
{% block content %}


<head>
    <title>Foro de comentarios</title>


    
    <style>
        .comment {
            margin-bottom: 20px;
            border: 2px solid #ccc; /* Añade un contorno de 1 píxel de ancho con color gris (#ccc) */
            border-radius: 30px;
            padding: 10px; /* Añade un espacio interno de 10 píxeles alrededor del contenido */
            width: 100%; /* Haz que el div ocupe todo el ancho disponible */
            box-sizing: border-box; /* Incluye el tamaño del borde en el ancho total del div */
            background-color: azure;
        }
        .like {
            border: 1px solid #ccc; /* Borde más pequeño */
            border-radius: 40px;
            padding: 10px;
            display: flex;
            align-items: center;
            justify-content: flex-end; /* Alinea la imagen a la derecha */
            background-color: #ffdddd;

        }



        .like .image-container{
            display: flex;
            align-items: center;
            justify-content: space-between;
            flex-grow: 1;
        }
    
        .comment .image-container {
            float: center;
            margin-left: 10px;
        }

        .like .image {
            width: 100px; /* Ajusta el tamaño de la imagen según tus preferencias */
            height: 100px; /* Ajusta el tamaño de la imagen según tus preferencias */
            object-fit: cover;
            border: 1px solid #ccc; /* Añade un contorno alrededor de la imagen */
            border-radius: 50%;
            order: 2;
            margin-right: 80px;

        }
    
        .comment .image {
            width: 90px; /* Ajusta el tamaño de la imagen según tus preferencias */
            height: 90px; /* Ajusta el tamaño de la imagen según tus preferencias */
            object-fit: cover;
            border: 1px solid #ccc; /* Añade un contorno alrededor de la imagen */
        }

        .comment .text {
            margin-top: 10px; /* Añade espacio encima del texto */
        }
    
        .comment .user-info {
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
        }

        .like .username{
            margin-right: 90px;
            font-size: xx-large;
            font-style: oblique;
            font-family: fantasy;
        }
    
        .comment .username {
            font-family: Verdana, Geneva, Tahoma, sans-serif;
            font-weight: bold;
            font-size: 1.2em; /* Ajusta el tamaño del nombre de usuario según tus preferencias */
            text-align: center;
        }
    
        .heart-icon {
            color: red; /* Ajusta el color del corazón según tus preferencias */
            font-size: 100px; /* Ajusta el tamaño del corazón según tus preferencias */
            font-style: italic;
        }
        .image-evento{
            margin-left: 110px;
        }


    </style>
    
</head>



<body>
    <div class="container">
        <h2>Interacciones</h2>
        <div class="row">
            <div class="col-md-6">
                {% for comentario in comentarios %}
                <div class="comment">
                    <div class="user-info">
                        <div class="image-container">
                            <a href="{% url 'show_event' id=comentario.evento.id %}" target="_blank"><img src="{{ comentario.evento.imagen.url }}" class="image" alt="Imagen de perfil comment"></a>
                            <div class="text">{{ comentario.evento.nombre }}</div>
                        </div>
                        <div>
                            <div class="username">{{ comentario.usuario.username }}</div>
                            <div class="date">{{ comentario.fecha_creacion }}</div>
                        </div>
                    </div>
                    <div class="text">{{ comentario.texto }}</div>
                </div>
                {% endfor %}
            </div>
<!---->
            <div class="col-md-6">
                {% for like in likes %}
                <div class="like">
                    <div class="username">{{ like.usuario.username }}</div>
                    <div class="heart-icon">&hearts;</div>
                    <a href="{% url 'show_event' id=like.evento.id %}" class="image-evento" target="_blank">
                      <img src="{{ like.evento.imagen.url }}" alt="Imagen de perfil like" class="image">
                    </a>
                    <br>
                </div>
                <br>
                {% endfor %}
            </div>
        </div>
    </div>
</body>




{% endblock %}

pagina/templates/create_event.html
{% extends "base.html" %}

{% block content %}
<h2>Crear un nuevo evento</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Crear Evento</button>
</form>
{% endblock %}

pagina/templates/edit_event.html
{% extends "base.html" %}

{% block content %}
  <h2>Editar evento: {{ evento.nombre }}</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Guardar Cambios</button>
  </form>
{% endblock %}

pagina/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <h2>Iniciar sesión</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Iniciar sesión</button>
    </form>
{% endblock %}

pagina/templates/logout.html
{% extends 'base.html' %}

{% block content %}
    <h2>Cerrar sesión</h2>
    <p>¿Estás seguro de que deseas cerrar sesión?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Cerrar sesión</button>
    </form>
{% endblock %}

pagina/templates/show_event.html
{% extends 'base.html' %}
{% block title %}{{ event.name }} info{% endblock %}
{% block header_title %}{{ subtitle }}{% endblock %}
{% block content %}
  <style>
    .container1 {
      margin-top: 20px;
      display: flex;
      justify-content: space-between;
      padding: 20px;
      border: 2px solid #ccc;
      box-shadow: 25px 15px #0833a2;
      background-color: whitesmoke;
    }

    .column {
      flex: 1;
      padding: 10px;
      margin: 5px;
      display: flex;
      flex-direction: column;
    }

    .text-section {
      border: 1px solid #ccc;
      padding-left: 5px;
    }

    .image-column {
      width: 20%;
    }

    .image-column img {
      width: 100%;
      height: auto;
    }

    .text-column {
      width: 60%;
      display: flex;
      flex-direction: column;
    }

    .info-section {
      margin-top: 20px;
      text-align: center;
      
    }

    .description-section {
      margin-top: 45px;
      text-align: center;
    }

    .number-count-section {
      display: flex;
      justify-content: space-between;
      margin-top: 20px;
    }

    .number-section,
    .count-section {
      text-align: center;
      width: 48%;
    }

    .attend-button {
      text-align: right; /* Cambiado a centrar */
      margin-top: 20px; /* Ajustado el margen */
      margin-right: 110px;
    }

    summary {
      font-size: x-large;
      font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
      font-weight: 200;
      text-decoration: underline;
    }

    .info-section .detalle {
      margin-top: 25px;
      font-family: Verdana, Geneva, serif, sans-serif;
      

    }

    .detalle {
      margin-top: 25px;
      font-family: Verdana, Geneva, serif, sans-serif;
    }

    .comentario {
      height: 65px;
      overflow-y:auto ; 
      font-family: monospace;
      
    }

    .heart-symbol {
      color: red;
      text-decoration: none;
    }
  </style>

  <title>Información del Evento</title>
</head>

<body>

  <div class="container1">
    <div class="column image-column">
      <!-- Contenido de la primera columna -->
      <img src="{{ event.imagen.url }}" class="img-thumbnail" alt="Event Image">
      <br>
      <br>
      <br>
      <div class="text-section">
        <h4 class="card-title" style="border: #ccc; font-family: 'Times New Roman', Times, serif; margin-top: 20px;">Comentarios</h4>
        <br>
        <div class="comentario">
          {% for comentario in comentarios %}
            <p>{{ comentario.usuario.username }}: {{ comentario.texto }}</p>
          {% endfor %}
        </div>

        <!-- Formulario para agregar comentarios -->
        {% if user.is_authenticated %}
          <form method="post" action="{% url 'show_event' id=event.id %}">
            {% csrf_token %}
            {{ comentario_form.as_p }}
            <button type="submit" class="btn btn-outline-primary">Enviar</button>
          </form>
        {% else %}
          <p>Inicia sesión para agregar un comentario.</p>
        {% endif %}
      </div>
    </div>
    <div class="column text-column">
      <!-- Contenido de la segunda columna -->
      <div class="info-section">
        <details open>
          <summary>Información del Evento</summary>
          <p class="detalle">
              <li>Nombre: {{ event.nombre }}</li>
              <li>Ubicación: {{ event.ubicacion }}</li>
              <li>Inicia: {{ event.fechaInicio }}</li>
              <li>Termina: {{ event.fechaFin }}</li>
          </p>
        </details>
      </div>
      <div class="description-section">
        <details open>
          <summary>Descripción</summary>
          <p class="detalle">{{ event.descripcion }}</p>
        </details>
      </div>
      <!-- Sección para el número y el conteo -->
      <div class="number-count-section">
        <div class="number-section">
          <p style="font-size: 35px;"> 
            <span> {{ event.like_set.count }}
              <a href= "{% url 'like_event' id=event.id %}" target="_blank" rel="noopener noreferrer">
                <span class="heart-symbol">&hearts;</span>
              </a>
            </span>
          </p>
        </div>
        <div class="count-section">
          <p style="font-size: 35px;">{{event.asistencia}}/{{event.capacidad}}</p>
        </div>
      </div>
      <!-- Botón para asistir (movido debajo del count-section) -->
      <div class="attend-button">
        <a href="{% url 'attend_event' id=event.id %}" class="btn btn-success">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar2-event" viewBox="0 0 16 16">
            <path d="M11 7.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5z"/>
            <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5M2 2a1 1 0 0 0-1 1v11a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1z"/>
            <path d="M2.5 4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H3a.5.5 0 0 1-.5-.5z"/>
          </svg>
          Asistir
        </a>
      </div>
      
    </div>
  </div>

</body>
{% endblock %}

pagina/templates/signup.html
{% extends 'base.html' %}

{% block content %}
    <h2>Registrarse</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Registrarse</button>
    </form>
{% endblock %}